language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# install codecov
before_install:
  - sudo mkdir /etc/pihole
  - sudo echo "1" > /etc/pihole/pihole.3.eventHorizon.txt
  - sudo echo "1" > /var/log/pihole.log
  - pip install codecov

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - coverage run tests.py

after_success:
  - codecov